export default {
  URL_API: '/api/ecommerce',
  URL_API_FORMAT: '/api/ecommerce/format',
  ADD: 'Añadir',
  UPDATE: 'Actualizar',
  EURO_SIGN: '€',
  MINUS_SIGN: '-',
  PLUS_SIGN: '+',
  MY_CART: 'MI CESTA',
  EMPTY_CART: 'Vaciar cesta',
  TOTAL: 'TOTAL',
  PRODUCTS: 'productos',
  BUY: 'COMPRAR',
  SHOP: 'SHOP',
  PRODUCT_DETAIL: 'PRODUCT DETAIL',
  NO_PRODUCT: 'No hay productos',
  ERASE: 'Borrar',
  FORMAT: 'Formato',
  SELECT_FORMAT: 'Selecciona formato',
  NAME: 'Nombre',
  STOCK: 'Stock',
  PRICE: 'Precio',
  IMAGE_URL: 'Url Imagen'
};
